/// Flutter icons IconChat
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconChat
///      fonts:
///       - asset: fonts/IconChat.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class IconChat {
  IconChat._();

  static const _kFontFam = 'IconChat';
  static const String? _kFontPkg = null;

  static const IconData chevron_left = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xf03d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone_slash = IconData(0xf131, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_slash = IconData(0xf4e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
    static const IconData phone_alt = IconData(0xf879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
