/// Flutter icons Icon_login
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon_login
///      fonts:
///       - asset: fonts/Icon_login.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names, camel_case_types

import 'package:flutter/widgets.dart';

class Icon_login {
  Icon_login._();

  static const _kFontFam = 'Icon_login';
  static const String? _kFontPkg = null;

  static const IconData user =
      IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xf023, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xf09c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus =
      IconData(0xf234, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_alt =
      IconData(0xf406, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_lock =
      IconData(0xf502, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
